" Internal Settings Start
source ~/.vim/autoload/plug.vim
source ~/.vim/plugins.vim
source ~/.vim/keybindings/general.vim

	" Autosave files
autocmd TextChanged,TextChangedI *.py silent write

	" Display row number
set number

	" Copy yanked text to clipboard
" set clipboard^=unnamed
set clipboard=unnamedplus

	" Set tab widht to 4 spaces
set tabstop=4
set shiftwidth=4

	" Word wrap by words, not characters
set wrap linebreak 

	" Relative Line Numbers
set number
set relativenumber

nnoremap k kzz
nnoremap j jzz

syntax on
" filetype plugin indent on
filetype plugin on
" autocmd FileType vim setlocal commentstring="\ %s"

" Internal Settings End


" Plugins


	" Omnisearch Start

" filetype plugin on
" set omnifunc=syntaxcomlete#Complete

	" Omnisearch End


	" Vundle Start

" set nocompatible " be improved, required
" filetype off "required
